port: 8088
host: localhost
auth:
  github:
    clientId: 619497416ea57bbd0d42
    clientSecret: 0d7132fc541f20a3990cba5381ef2b47221bc480
    
  keycloak:
    realm: master
    auth-server-url: http://localhost:8080/auth  
    verify-token-audience: true
    policy-enforcer: {}
    ssl-required: external
    resource: vertx
    credentials:
      secret: d2b5f235-79c5-4f8f-b1bd-d1f99ade2241
    confidential-port: 0
