port: 8090
host: localhost
auth:
  github:
    clientId: 619497416ea57bbd0d42
    clientSecret: 0d7132fc541f20a3990cba5381ef2b47221bc480
    
  keycloak:
    realm: master
    auth-server-url: http://localhost:8080/auth  
    verify-token-audience: true
    policy-enforcer: {}
    ssl-required: external
    resource: vertx
    credentials:
      secret: aea3bae2-5938-45eb-b529-16508d74e4ee
    confidential-port: 0
